### ISSUE TITLE
Templating language: getting widgets to show up

### ISSUE THREAD

**Issue by camertron** [voidlabs/mosaico#358]
Hey guys,

I'm having a devil of a time figuring out how to make individual widgets appear under the "Styles" tab for this custom template I'm working on. Here are the applicable rules:

```css
/* helpers */
src { label: Image; widget: src; }
url { label: Link; widget: url; }

/* base properties */
image { label: Image; properties: src url alt; }
text { label: Paragraph; widget: text; }
color { label: Color; widget: color; }
size { label: Size; widget: select; options: 8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31; }

/* derived properties */
backgroundColor { label: Background Color; extend: color; }
headerText { label: Header Text; properties: color size; extend: text; }

/* blocks */
topBarBlock { label: Top Bar; properties: buttonVisible }
heroBlock { label: Hero Header; properties: image backgroundColor headerText; }
```

The HTML looks like this:

```html
<table width='100%' data-ko-block="heroBlock">
  <tr>
    <td align='center' style="padding: 54px 15px 54px 15px; background-color: #0E91A1; -ko-background-color: @backgroundColor; -ko-attr-bgcolor: @backgroundColor" class='td'>
      <table width='584' class='table'>
        <tr>
          <td align="center" style="color:white;">
            <p class='h1' data-ko-editable="headerText" style="font-size: 21px; color: white; -ko-font-size: @[headerText.size]px; -ko-color: @[headerText.color]">
              Header Text
            </p>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
```

Unfortunately the editor doesn't show the size or color widgets when the header item is selected:

![image](https://user-images.githubusercontent.com/575280/29682588-6628450e-88c0-11e7-9882-fa2e5ba25052.png)

Moreover, Mosaico is printing `[object Object]` where I would expect to see `Header Text`. I assume this is because I need to put something in like `-ko-bind-text` or `@[headerText.text]` but neither of those are working.

I feel like I'm fundamentally misunderstanding how the templating language is supposed to work, but I've tried a _ton_ of combinations and haven't been able to figure it out. Any help you could provide would be much appreciated!

**Browser**: Chrome 60.0.3112.90
**Backend**: Rails (of my own making)

**Comment by bago** [comment]
```
headerText { label: Header Text; properties: color size; extend: text; }
```

if you "extend: text" then "headerText" is a "simple string", on the other side if you define "properties" then you are defining an object. So this declaration is invalid (maybe the javascript console tells you about this).

so change to
```css
headerText { label: Header Text; extend: text; }
headerTextStyle { label: Header Text Style; properties: color size; }
```
and 
```html
<p class='h1' data-ko-editable="headerText" style="font-size: 21px; color: white; -ko-font-size: @[headerTextStyle.size]px; -ko-color: @[headerTextStyle.color]">
              Header Text
            </p>
```
