### ISSUE TITLE
default value for select widget

### ISSUE THREAD

**Issue by InfGame** [voidlabs/mosaico#701]
Heya! I have a select widget for a color theme that i use in many templates of mine:

```css
colorStyle {
  label: Color;
  widget: select;
  options: Red=Rot|Green=Grün|Blue=Taubenblau|DarkBlue=Dunkelblau|Oliv|Neutral;
}
```

Tho i would like a different theme to be the default on different templates.

Is there any way to define a default value on a select widget?
